version: "3"

services: 
    app:
        build: 
            context: .
        volumes: 
            - ./app:/app
        command: >
            sh -c "python -m pytest -v --cov &&
            python menu.py"
